typography_spectrum: 0.8167195816058666
color:
  brandStrength: 0.4257054526824504
  lightness: 0.6850514442194253
  saturation: 0.44844258017838
  rhythmicContrast: 0.5716210620012134
  brandColors:
    - '#FFFFFF'
    - '#B7CA79'
    - '#F7E8B1'
    - '#8A715B'
    - '#CFD1C3'
layout_spectrum: 0.4314906755462289
author:
  name: Urra
  email: design.urra@gmail.com
  url: 'http://alberto-urra.blogspot.co.uk/'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/8a0f9e7e-e21e-489c-b121-e5a0c7e4a6b1.png
name: Nadia Rabosio
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/5adb0c2d-50a2-4361-b410-418a7b2c3e59.png
title: Natural Woman
description: nrbijoux.co.uk
